version: "1.0.0.0"

services: 
  ProductCatalog:
    container_name: ProductCatalog
    build: 
      context: ../
      dockerfile: Docker/ProductCatalog/Dockerfile
    image: "product-catalog"
    ports:
      - "3000:80"
  ShoppingCart:
    container_name: ShoppingCart
    build:
      context: ../
      dockerfile: Docker/ShoppingCart/Dockerfile
    image: "shopping-cart"
    ports:
      - "3001:80"
    links:
      - product-catalog