version: "2"

services: 
  ProductCatalog:
    container_name: ProductCatalog
    build: 
      context: ../
      dockerfile: Docker/ProductCatalog/Dockerfile
    image: "product-catalog"
    ports:
      - "3000:80"
    depends_on: 
      - "redis"
  ShoppingCart:
    container_name: ShoppingCart
    build:
      context: ../
      dockerfile: Docker/ShoppingCart/Dockerfile
    image: "shopping-cart"
    ports:
      - "3001:80"
    depends_on:
      - "ProductCatalog"
  ActivityLogger:
    container_name: ActivityLogger
    build:
      context: ../
      dockerfile: Docker/ActivityLogger/Dockerfile
    image: "activity-logger"
    ports:
      - "3002:80"
    depends_on:
      - "ShoppingCart"
  redis:
    container_name: Redis
    image: "redis"
    ports:
      - "6379:6379"
    volumes:
      - redis-db:/data
volumes: 
  redis-db:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/Users/kravcov/Public/MyGitHub/CSharp-Core/MicroCommerce/db-data/redis'